# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(829, 609)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.list_facts = QtWidgets.QListView(self.centralwidget)
        self.list_facts.setMaximumSize(QtCore.QSize(300, 16777215))
        self.list_facts.setObjectName("list_facts")
        self.horizontalLayout.addWidget(self.list_facts)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.txt_name = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.txt_name.setFont(font)
        self.txt_name.setObjectName("txt_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txt_name)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.txt_per_sec = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txt_per_sec.setFont(font)
        self.txt_per_sec.setObjectName("txt_per_sec")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txt_per_sec)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.list_in = QtWidgets.QListView(self.centralwidget)
        self.list_in.setObjectName("list_in")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.list_in)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.list_out = QtWidgets.QListView(self.centralwidget)
        self.list_out.setObjectName("list_out")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.list_out)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.cbx_enable = QtWidgets.QCheckBox(self.centralwidget)
        self.cbx_enable.setObjectName("cbx_enable")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.cbx_enable)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.txt_energy = QtWidgets.QLabel(self.centralwidget)
        self.txt_energy.setObjectName("txt_energy")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.txt_energy)
        self.txt_state = QtWidgets.QLabel(self.centralwidget)
        self.txt_state.setObjectName("txt_state")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.txt_state)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.bar_current = QtWidgets.QProgressBar(self.centralwidget)
        self.bar_current.setProperty("value", 24)
        self.bar_current.setObjectName("bar_current")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.bar_current)
        self.horizontalLayout.addLayout(self.formLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 829, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Название"))
        self.txt_name.setText(_translate("MainWindow", "Шахта"))
        self.label_2.setText(_translate("MainWindow", "Товара в секунду"))
        self.txt_per_sec.setText(_translate("MainWindow", "2.5"))
        self.label_5.setText(_translate("MainWindow", "Что производит"))
        self.label_6.setText(_translate("MainWindow", "Что требуется"))
        self.label_7.setText(_translate("MainWindow", "Статус"))
        self.cbx_enable.setText(_translate("MainWindow", "Включено"))
        self.label_10.setText(_translate("MainWindow", "Состояние"))
        self.label_8.setText(_translate("MainWindow", "Потребение энергии"))
        self.txt_energy.setText(_translate("MainWindow", "100"))
        self.txt_state.setText(_translate("MainWindow", "Не работает-Не хватает энергии"))
        self.label_12.setText(_translate("MainWindow", "Производство"))

